### ISSUE TITLE
Add Manual Start State Machine And Manual Assign First State (Current State At First)

### ISSUE THREAD

**Issue by takaaptech** [tomori-hikage/state-machine#1]
Hi!
Your FSM using Unirx is awesome! I find it fits my need
For easier usage, I think we should add the feature that allows set autostart (Call via Start function) or manually start FSM.
Also, We should have a function to assign the first function if need, for now, we only allow drag and drop from Hierarchy.
Thanks so much!

**Comment by right2sky** [comment]
今月中に確認いたします、ありがとうございます！
